name: build

on: [push, pull_request]

jobs:
  build_app_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build --rm -f base.alpine/Dockerfile -t base.app:latest base.alpine
      
  build_go_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build --rm -f build.go/Dockerfile -t build.go:latest build.go
 
